# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
# Header
menu:
  Home: 
  Archives: /archives
  
# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: Share
fancybox: true

#avatar 
avatar: https://picsshine.oss-cn-shenzhen.aliyuncs.com/blogpics/ishien-头像.png

# Site
title: 闲谈梦落花
subtitle: 
description: 长路漫漫离家，伴君不负韶华。
author: shineee
language: zh-CN
timezone: Asia/Shanghai


# Miscellaneous
google_analytics:
#duoshuo_shortname: shineee
#duoshuo_share: true
rss: 
google_site_verification: 
baidu_analytics: 38cf35b14428fed12ee207849cffa5a6 
favicon: /favicon.ico
music: 
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.shineee.win/
root: /
permalink: :category/:abbrlink/
permalink_defaults:

#abbrlink配置
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: dec    # 进制：dec(default) and hex
#网易跟帖
wangYi: 


# Directory

source_dir: source # 资源文件夹 存放内容
public_dir: public # 公共文件夹 存放站点文件
tag_dir: tags  # 标签文件夹
archive_dir: archives  #归档文件夹
category_dir: categories #分类
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository:  https://github_token@github.com/orangeshinee/orangeshinee.github.io.git
  branch: master


# 豆瓣评书
douban:
  user: shine-smile
  builtin: false
  book:
    title: '书山有路'
    quote: '天道酬勤'
  movie:
    title: '光影流年'
    quote: 'Youth is wasted on the young.'
  timeout: 10000

# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  exclude:
    - '**/*.min.js' 
    - '**/cliclove.js'
    - '**/image.js' 
    - '**/valine.js' 
    - '**/linkcard.js' 
    - '**/clicksocialvalue.js' 

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: false
  exclude_codeblock: true

