<script type="text/javascript" src="/js/cliclove.js"></script>

<script type="text/javascript" src="/js/crash_cheat.js"></script>
<link href="https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,700,700i|Ma+Shan+Zheng|Mansalva|Noto+Sans+SC:400,500,700|Noto+Serif+SC:400,700|Noto+Serif+TC:400,500,700|ZCOOL+XiaoWei&display=swap&subset=chinese-simplified,greek-ext,latin-ext" rel="stylesheet">

